### ISSUE TITLE
[Feature request] App settings

### ISSUE THREAD

**Issue by keptsecret** [kevinsadi/lei3d#51]
Implement AppSettings class that will read from an .ini file on startup and store the settings inside the class variables.  
Make value access static, so we can call `AppSetting::FOV`.

Need following values used as setting for now:

* screen resolution
* fullscreen or windowed
* fov
* mouse sensitivity

First two values are used in the `initialize()` of the Application class to create the GLFW window. The other two are used in camera constructor. The .ini file can be read/edited as a normal text file, so it can just look like:

```
screensize:
    width: 1920
    height: 1080
fullscreen: 0
fov: 90
mousespeed: 5
```

(0/1 for booleans)
